services:
  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    container_name: backend-java
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appunture
      - SPRING_DATASOURCE_USERNAME=appunture
      - SPRING_DATASOURCE_PASSWORD=appunture
      - SPRING_PROFILES_ACTIVE=dev
      - APP_SECURITY_JWT_SECRET=CHANGEME_BASE64_SECRET
    depends_on:
      - db
    volumes:
      - ./backend-java/uploads:/app/uploads


  frontend-mobile:
    build:
      context: ./frontend-mobile
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend-mobile:/app

  db:
    image: postgres:14
    container_name: appunture-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=appunture
      - POSTGRES_PASSWORD=appunture
      - POSTGRES_DB=appunture
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
