global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: appunture-backend
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - backend-java:8080
